# Generated by Django 5.2.12 on 2026-04-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_code", models.CharField(max_length=64, unique=True)),
                ("task_name", models.CharField(max_length=128)),
                (
                    "scene_type",
                    models.CharField(
                        choices=[
                            ("forest", "forest"),
                            ("agri", "agri"),
                            ("mixed", "mixed"),
                        ],
                        default="mixed",
                        max_length=32,
                    ),
                ),
                ("priority", models.IntegerField(default=3)),
                ("status", models.CharField(default="pending", max_length=32)),
                (
                    "command_center",
                    models.CharField(
                        default="Chongqing Command Center", max_length=128
                    ),
                ),
                ("creator_id", models.BigIntegerField(default=0)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("planned_start", models.DateTimeField(blank=True, null=True)),
                ("planned_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "global_task",
                "verbose_name_plural": "global_task",
                "db_table": "tasking_global_task",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="TaskDispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("global_task_id", models.BigIntegerField(default=0)),
                ("dispatch_code", models.CharField(max_length=64, unique=True)),
                (
                    "target_db",
                    models.CharField(
                        choices=[("forest", "forest"), ("agri", "agri")], max_length=32
                    ),
                ),
                ("target_task_id", models.BigIntegerField(default=0)),
                ("drone_group_id", models.BigIntegerField(default=0)),
                ("dispatch_status", models.CharField(default="created", max_length=32)),
                ("dispatcher_id", models.BigIntegerField(default=0)),
                ("dispatched_at", models.DateTimeField(auto_now_add=True)),
                ("remark", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "task_dispatch",
                "verbose_name_plural": "task_dispatch",
                "db_table": "tasking_task_dispatch",
                "ordering": ["-id"],
            },
        ),
    ]
