# Generated by Django 5.2.13 on 2026-04-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasking", "0002_add_primary_drone_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="globaltask",
            name="terrain_area_id",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
