# Generated by Django 5.2.12 on 2026-04-11 00:45

import django.contrib.auth.validators
import django.utils.timezone
import system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operator_id", models.BigIntegerField(default=0)),
                ("operator_name", models.CharField(max_length=64)),
                ("module", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=64)),
                ("request_method", models.CharField(blank=True, max_length=16)),
                ("request_path", models.CharField(blank=True, max_length=255)),
                ("request_ip", models.CharField(blank=True, max_length=64)),
                ("extra_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "system_operation_log",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_code", models.CharField(max_length=64, unique=True)),
                ("role_name", models.CharField(max_length=64)),
                ("permissions", models.JSONField(default=list)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "system_role_permission",
            },
        ),
        migrations.CreateModel(
            name="SystemUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "real_name",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="真实姓名"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=32, verbose_name="手机号"),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("super_admin", "超级管理员"),
                            ("dispatcher", "调度员"),
                            ("pilot", "飞手"),
                            ("forest_officer", "林业专员"),
                            ("agri_officer", "农业专员"),
                        ],
                        default="dispatcher",
                        max_length=32,
                    ),
                ),
                ("roles", models.JSONField(default=list, verbose_name="角色列表")),
                (
                    "department",
                    models.CharField(blank=True, max_length=128, verbose_name="部门"),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="所属区域"
                    ),
                ),
                (
                    "last_login_ip",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="最后登录IP"
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=255, verbose_name="备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统用户",
                "verbose_name_plural": "系统用户",
                "db_table": "system_user",
            },
            managers=[
                ("objects", system.models.SystemUserManager()),
            ],
        ),
    ]
