# Generated by Django 5.2.12 on 2026-04-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rolepermission",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="systemuser",
            options={
                "verbose_name": "system_user",
                "verbose_name_plural": "system_user",
            },
        ),
        migrations.AlterField(
            model_name="systemuser",
            name="department",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="systemuser",
            name="last_login_ip",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="systemuser",
            name="phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="systemuser",
            name="real_name",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="systemuser",
            name="region",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="systemuser",
            name="remark",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="systemuser",
            name="roles",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="systemuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("super_admin", "super_admin"),
                    ("dispatcher", "dispatcher"),
                    ("pilot", "pilot"),
                    ("forest_officer", "forest_officer"),
                    ("agri_officer", "agri_officer"),
                ],
                default="dispatcher",
                max_length=32,
            ),
        ),
    ]
