# Generated by Django 5.2.12 on 2026-04-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FireDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patrol_task_id", models.BigIntegerField(default=0)),
                ("forest_area_id", models.BigIntegerField(default=0)),
                ("alert_level", models.CharField(default="yellow", max_length=32)),
                ("fire_status", models.CharField(default="suspected", max_length=32)),
                (
                    "longitude",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "latitude",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "heat_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "fire_detection",
                "verbose_name_plural": "fire_detection",
                "db_table": "forest_fire_detection",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ForestArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_code", models.CharField(max_length=64, unique=True)),
                ("area_name", models.CharField(max_length=128)),
                ("region", models.CharField(max_length=128)),
                ("risk_level", models.CharField(default="medium", max_length=32)),
                (
                    "coverage_km2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("manager_name", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "forest_area",
                "verbose_name_plural": "forest_area",
                "db_table": "forest_area",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ForestPatrolTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_code", models.CharField(max_length=64, unique=True)),
                ("global_task_id", models.BigIntegerField(default=0)),
                ("area_id", models.BigIntegerField(default=0)),
                ("drone_group_id", models.BigIntegerField(default=0)),
                ("patrol_type", models.CharField(default="routine", max_length=32)),
                ("status", models.CharField(default="pending", max_length=32)),
                ("planned_start", models.DateTimeField(blank=True, null=True)),
                ("planned_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "forest_patrol_task",
                "verbose_name_plural": "forest_patrol_task",
                "db_table": "forest_patrol_task",
                "ordering": ["-id"],
            },
        ),
    ]
