# Generated by Django 5.2.12 on 2026-04-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drone_code", models.CharField(max_length=64, unique=True)),
                ("drone_name", models.CharField(max_length=128)),
                ("model_name", models.CharField(max_length=128)),
                ("serial_no", models.CharField(max_length=128, unique=True)),
                (
                    "max_payload",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "battery_capacity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("status", models.CharField(default="idle", max_length=32)),
                ("launch_site_id", models.BigIntegerField(default=0)),
                ("pilot_id", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "drone",
                "verbose_name_plural": "drone",
                "db_table": "fleet_drone",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="DroneGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_code", models.CharField(max_length=64, unique=True)),
                ("group_name", models.CharField(max_length=128)),
                ("scene_type", models.CharField(default="mixed", max_length=32)),
                ("command_level", models.CharField(default="regional", max_length=32)),
                ("status", models.CharField(default="standby", max_length=32)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "drone_group",
                "verbose_name_plural": "drone_group",
                "db_table": "fleet_drone_group",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="LaunchSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(max_length=128)),
                ("region", models.CharField(max_length=128)),
                (
                    "longitude",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "latitude",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "altitude",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("status", models.CharField(default="ready", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "launch_site",
                "verbose_name_plural": "launch_site",
                "db_table": "fleet_launch_site",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Pilot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_user_id", models.BigIntegerField(default=0)),
                ("pilot_name", models.CharField(max_length=64)),
                ("license_no", models.CharField(max_length=64, unique=True)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("skill_level", models.CharField(default="A", max_length=32)),
                ("status", models.CharField(default="idle", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "pilot",
                "verbose_name_plural": "pilot",
                "db_table": "fleet_pilot",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="DroneGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_id", models.BigIntegerField()),
                ("drone_id", models.BigIntegerField()),
                ("role_name", models.CharField(default="worker", max_length=64)),
                ("join_status", models.CharField(default="active", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "drone_group_member",
                "verbose_name_plural": "drone_group_member",
                "db_table": "fleet_drone_group_member",
                "ordering": ["-id"],
                "unique_together": {("group_id", "drone_id")},
            },
        ),
    ]
