# Generated by Django 5.2.13 on 2026-04-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="drone",
            name="terrain_id",
            field=models.BigIntegerField(default=0, verbose_name="绑定地形ID"),
        ),
    ]
