# Generated by Django 5.2.13 on 2026-04-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0002_drone_terrain_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="drone",
            name="battery_percentage",
            field=models.IntegerField(default=100, verbose_name="当前电量百分比"),
        ),
        migrations.AddField(
            model_name="drone",
            name="bound_terrain_id",
            field=models.BigIntegerField(default=0, verbose_name="关联地形区域ID"),
        ),
        migrations.AddField(
            model_name="drone",
            name="last_active",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最近活动时间"
            ),
        ),
    ]
