# Generated by Django 5.2.12 on 2026-04-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgriTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_code", models.CharField(max_length=64, unique=True)),
                ("global_task_id", models.BigIntegerField(default=0)),
                ("farm_plot_id", models.BigIntegerField(default=0)),
                ("drone_group_id", models.BigIntegerField(default=0)),
                ("task_type", models.CharField(default="spray", max_length=32)),
                ("pesticide_name", models.CharField(blank=True, max_length=128)),
                ("status", models.CharField(default="pending", max_length=32)),
                ("planned_start", models.DateTimeField(blank=True, null=True)),
                ("planned_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "agri_task",
                "verbose_name_plural": "agri_task",
                "db_table": "agri_task",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="FarmPlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plot_code", models.CharField(max_length=64, unique=True)),
                ("plot_name", models.CharField(max_length=128)),
                ("region", models.CharField(blank=True, max_length=128)),
                ("owner_name", models.CharField(blank=True, max_length=64)),
                ("crop_type", models.CharField(default="rice", max_length=64)),
                (
                    "area_mu",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "longitude",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "latitude",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("risk_level", models.CharField(default="medium", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "farm_plot",
                "verbose_name_plural": "farm_plot",
                "db_table": "agri_farm_plot",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="PestMonitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agri_task_id", models.BigIntegerField(default=0)),
                ("farm_plot_id", models.BigIntegerField(default=0)),
                ("pest_type", models.CharField(default="unknown", max_length=64)),
                ("severity", models.CharField(default="medium", max_length=32)),
                (
                    "coverage_ratio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "pest_monitor",
                "verbose_name_plural": "pest_monitor",
                "db_table": "agri_pest_monitor",
                "ordering": ["-id"],
            },
        ),
    ]
