# Generated by Django 5.2.13 on 2026-04-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agri", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmplot",
            name="terrain_id",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
