# Generated by Django 5.2.12 on 2026-04-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FederationQueryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_code", models.CharField(max_length=64, unique=True)),
                ("query_name", models.CharField(max_length=128)),
                ("query_scope", models.CharField(default="forest,agri", max_length=64)),
                (
                    "source_dbs",
                    models.CharField(default="default,forest,agri", max_length=64),
                ),
                ("result_count", models.IntegerField(default=0)),
                ("query_status", models.CharField(default="success", max_length=32)),
                ("remark", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "federation_query_record",
                "verbose_name_plural": "federation_query_record",
                "db_table": "federation_query_record",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="FederationStatSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_code", models.CharField(max_length=64, unique=True)),
                ("stat_date", models.DateField()),
                ("central_task_count", models.IntegerField(default=0)),
                ("forest_event_count", models.IntegerField(default=0)),
                ("agri_event_count", models.IntegerField(default=0)),
                ("total_dispatch_count", models.IntegerField(default=0)),
                (
                    "snapshot_status",
                    models.CharField(default="generated", max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "federation_stat_snapshot",
                "verbose_name_plural": "federation_stat_snapshot",
                "db_table": "federation_stat_snapshot",
                "ordering": ["-id"],
            },
        ),
    ]
