# Generated by Django 5.2.12 on 2026-04-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("federation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="federationqueryrecord",
            name="requester_id",
            field=models.BigIntegerField(default=0),
        ),
    ]
