# Generated by Django 5.2.12 on 2026-04-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DroneHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drone_id", models.BigIntegerField(default=0)),
                ("drone_code", models.CharField(max_length=64)),
                ("heartbeat_status", models.CharField(default="online", max_length=32)),
                (
                    "cpu_usage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "memory_usage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("network_delay_ms", models.IntegerField(default=0)),
                ("heartbeat_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "drone_heartbeat",
                "verbose_name_plural": "drone_heartbeat",
                "db_table": "telemetry_drone_heartbeat",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="FlightTrajectory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drone_id", models.BigIntegerField(default=0)),
                ("global_task_id", models.BigIntegerField(default=0)),
                ("seq_no", models.IntegerField(default=1)),
                (
                    "longitude",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "latitude",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "altitude",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "speed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("sampled_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "flight_trajectory",
                "verbose_name_plural": "flight_trajectory",
                "db_table": "telemetry_flight_trajectory",
                "ordering": ["drone_id", "seq_no"],
            },
        ),
        migrations.CreateModel(
            name="TelemetrySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drone_id", models.BigIntegerField(default=0)),
                ("drone_code", models.CharField(max_length=64)),
                (
                    "battery_level",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
                (
                    "altitude",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "speed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "longitude",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "latitude",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("flight_status", models.CharField(default="idle", max_length=32)),
                ("signal_strength", models.IntegerField(default=100)),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "telemetry_snapshot",
                "verbose_name_plural": "telemetry_snapshot",
                "db_table": "telemetry_snapshot",
                "ordering": ["-id"],
            },
        ),
    ]
