# Generated by Django 5.2.13 on 2026-04-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Terrain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("terrain_code", models.CharField(max_length=64, unique=True)),
                ("terrain_name", models.CharField(max_length=128)),
                ("terrain_type_id", models.BigIntegerField(default=0)),
                ("region", models.CharField(blank=True, max_length=128)),
                (
                    "area_mu",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "longitude",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "latitude",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "farm_plot_id",
                    models.BigIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "forest_area_id",
                    models.BigIntegerField(blank=True, default=0, null=True),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "terrain",
                "verbose_name_plural": "terrain",
                "db_table": "terrain",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="TerrainFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("terrain_id", models.BigIntegerField(default=0)),
                (
                    "slope",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "elevation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("soil_type", models.CharField(blank=True, max_length=64)),
                (
                    "vegetation_coverage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "terrain_feature",
                "verbose_name_plural": "terrain_feature",
                "db_table": "terrain_feature",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="TerrainType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_code", models.CharField(max_length=32, unique=True)),
                ("type_name", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "terrain_type",
                "verbose_name_plural": "terrain_type",
                "db_table": "terrain_type",
                "ordering": ["-id"],
            },
        ),
    ]
