# Generated by Django 5.2.13 on 2026-04-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terrain", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TerrainFeature",
        ),
        migrations.DeleteModel(
            name="TerrainType",
        ),
        migrations.AlterModelOptions(
            name="terrain",
            options={"verbose_name": "地形", "verbose_name_plural": "地形"},
        ),
        migrations.RemoveField(
            model_name="terrain",
            name="area_mu",
        ),
        migrations.RemoveField(
            model_name="terrain",
            name="farm_plot_id",
        ),
        migrations.RemoveField(
            model_name="terrain",
            name="forest_area_id",
        ),
        migrations.RemoveField(
            model_name="terrain",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="terrain",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="terrain",
            name="region",
        ),
        migrations.RemoveField(
            model_name="terrain",
            name="terrain_code",
        ),
        migrations.RemoveField(
            model_name="terrain",
            name="terrain_name",
        ),
        migrations.RemoveField(
            model_name="terrain",
            name="terrain_type_id",
        ),
        migrations.AddField(
            model_name="terrain",
            name="area",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="面积（公顷）"
            ),
        ),
        migrations.AddField(
            model_name="terrain",
            name="coordinates",
            field=models.JSONField(default=list, verbose_name="坐标数据"),
        ),
        migrations.AddField(
            model_name="terrain",
            name="name",
            field=models.CharField(
                default="未命名地形", max_length=100, verbose_name="地形名称"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="terrain",
            name="risk_level",
            field=models.CharField(
                choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                default="低",
                max_length=20,
                verbose_name="风险等级",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="terrain",
            name="type",
            field=models.CharField(
                choices=[
                    ("mountain", "山地"),
                    ("hill", "丘陵"),
                    ("valley", "山谷"),
                    ("plateau", "高原"),
                    ("plain", "平原"),
                    ("forest", "林区"),
                    ("farm", "农田"),
                    ("mixed", "混合"),
                ],
                default="mountain",
                max_length=50,
                verbose_name="地形类型",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="terrain",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="terrain",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="terrain",
            name="description",
            field=models.TextField(blank=True, verbose_name="描述"),
        ),
        migrations.AlterModelTable(
            name="terrain",
            table=None,
        ),
    ]
