# Generated by Django 5.2.13 on 2026-04-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terrain", "0002_delete_terrainfeature_delete_terraintype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TerrainPlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "map_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="所属地图ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="地块名称")),
                (
                    "land_type",
                    models.CharField(
                        choices=[
                            ("forest", "林区"),
                            ("farmland", "农田"),
                            ("water", "水域"),
                            ("road", "道路"),
                            ("building", "建筑"),
                            ("mixed", "混合"),
                        ],
                        max_length=50,
                        verbose_name="地块类型",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                ("area", models.FloatField(default=0.0, verbose_name="面积")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "center_lng",
                    models.FloatField(blank=True, null=True, verbose_name="中心点经度"),
                ),
                (
                    "center_lat",
                    models.FloatField(blank=True, null=True, verbose_name="中心点纬度"),
                ),
                (
                    "geom_json",
                    models.JSONField(default=dict, verbose_name="GeoJSON 轮廓"),
                ),
                (
                    "grid_json",
                    models.JSONField(default=dict, verbose_name="网格绘制数据"),
                ),
                (
                    "style_json",
                    models.JSONField(default=dict, verbose_name="样式和图层信息"),
                ),
                ("meta_json", models.JSONField(default=dict, verbose_name="扩展信息")),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="创建者"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
            ],
            options={
                "verbose_name": "地块",
                "verbose_name_plural": "地块",
                "db_table": "terrain_plot",
                "indexes": [
                    models.Index(
                        fields=["map_id"], name="terrain_plo_map_id_915e09_idx"
                    ),
                    models.Index(
                        fields=["is_deleted"], name="terrain_plo_is_dele_fc8ce1_idx"
                    ),
                ],
            },
        ),
    ]
