# Generated by Django 5.2.13 on 2026-04-13 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terrain", "0003_terrainplot"),
    ]

    operations = [
        migrations.CreateModel(
            name="TerrainArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="区域名称")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mountain", "山地"),
                            ("hill", "丘陵"),
                            ("valley", "山谷"),
                            ("plateau", "高原"),
                            ("plain", "平原"),
                            ("forest", "林区"),
                            ("farm", "农田"),
                            ("mixed", "混合"),
                        ],
                        max_length=50,
                        verbose_name="区域类型",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="面积（公顷）",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "center_lng",
                    models.FloatField(blank=True, null=True, verbose_name="中心点经度"),
                ),
                (
                    "center_lat",
                    models.FloatField(blank=True, null=True, verbose_name="中心点纬度"),
                ),
                (
                    "boundary_json",
                    models.JSONField(default=dict, verbose_name="边界数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "区域",
                "verbose_name_plural": "区域",
            },
        ),
        migrations.CreateModel(
            name="TerrainElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="要素名称")),
                ("type", models.CharField(max_length=50, verbose_name="要素类型")),
                ("area", models.FloatField(default=0.0, verbose_name="面积")),
                (
                    "geom_json",
                    models.JSONField(default=dict, verbose_name="GeoJSON 轮廓"),
                ),
                ("meta_json", models.JSONField(default=dict, verbose_name="扩展信息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "要素",
                "verbose_name_plural": "要素",
                "db_table": "terrain_element",
            },
        ),
        migrations.CreateModel(
            name="TerrainZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="地块名称")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("forest", "林区"),
                            ("farmland", "农田"),
                            ("water", "水域"),
                            ("road", "道路"),
                            ("building", "建筑"),
                            ("mixed", "混合"),
                        ],
                        max_length=50,
                        verbose_name="地块分类",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="地块类型"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                ("area", models.FloatField(default=0.0, verbose_name="面积")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "geom_json",
                    models.JSONField(default=dict, verbose_name="GeoJSON 轮廓"),
                ),
                (
                    "grid_json",
                    models.JSONField(default=dict, verbose_name="网格绘制数据"),
                ),
                ("style_json", models.JSONField(default=dict, verbose_name="样式信息")),
                ("meta_json", models.JSONField(default=dict, verbose_name="扩展信息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "area_obj",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="terrain.terrainarea",
                        verbose_name="所属区域",
                    ),
                ),
            ],
            options={
                "verbose_name": "地块",
                "verbose_name_plural": "地块",
                "db_table": "terrain_zone",
            },
        ),
        migrations.DeleteModel(
            name="Terrain",
        ),
        migrations.DeleteModel(
            name="TerrainPlot",
        ),
        migrations.AddField(
            model_name="terrainelement",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elements",
                to="terrain.terrainzone",
                verbose_name="所属地块",
            ),
        ),
    ]
