# Generated by Django 5.2.13 on 2026-04-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terrain", "0004_terrainarea_terrainelement_terrainzone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TerrainSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50, verbose_name="大类")),
                ("name", models.CharField(max_length=100, verbose_name="子类别名称")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "子类别",
                "verbose_name_plural": "子类别",
                "unique_together": {("category", "name")},
            },
        ),
    ]
