# Generated by Django 5.2.12 on 2026-04-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terrain", "0005_terrainsubcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="terrainarea",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否删除"),
        ),
        migrations.AlterField(
            model_name="terrainarea",
            name="type",
            field=models.CharField(
                choices=[
                    ("mountain", "山地"),
                    ("hill", "丘陵"),
                    ("valley", "山谷"),
                    ("plateau", "高原"),
                    ("plain", "平原"),
                    ("forest", "林区"),
                    ("farm", "农田"),
                ],
                max_length=50,
                verbose_name="区域类型",
            ),
        ),
        migrations.AlterField(
            model_name="terrainzone",
            name="category",
            field=models.CharField(
                choices=[
                    ("forest", "林区"),
                    ("farmland", "农田"),
                    ("water", "水域"),
                    ("road", "道路"),
                    ("building", "建筑"),
                ],
                max_length=50,
                verbose_name="地块分类",
            ),
        ),
    ]
