# Generated by Django 5.2.13 on 2026-04-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terrain", "0006_terrainarea_is_deleted_alter_terrainarea_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="terrainsubcategory",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="是否为系统默认"),
        ),
        migrations.AlterField(
            model_name="terrainzone",
            name="category",
            field=models.CharField(
                choices=[
                    ("forest", "林区"),
                    ("farmland", "农田"),
                    ("water", "水域"),
                    ("road", "道路"),
                    ("building", "建筑"),
                    ("bare", "裸地"),
                ],
                max_length=50,
                verbose_name="地块分类",
            ),
        ),
    ]
