# Generated by Django 5.2.13 on 2026-04-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terrain", "0007_terrainsubcategory_is_default_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="terrainelement",
            options={"verbose_name": "标记", "verbose_name_plural": "标记"},
        ),
        migrations.AlterField(
            model_name="terrainelement",
            name="name",
            field=models.CharField(max_length=255, verbose_name="标记名称"),
        ),
        migrations.AlterField(
            model_name="terrainelement",
            name="type",
            field=models.CharField(max_length=50, verbose_name="标记类型"),
        ),
    ]
