# Generated by Django 5.2.13 on 2026-04-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terrain", "0008_alter_terrainelement_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.BigIntegerField(verbose_name="关联任务ID")),
                ("drone_id", models.BigIntegerField(verbose_name="使用无人机ID")),
                (
                    "drone_name",
                    models.CharField(max_length=128, verbose_name="无人机名称"),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                (
                    "status",
                    models.CharField(
                        default="pending", max_length=32, verbose_name="班次状态"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "测绘班次",
                "verbose_name_plural": "测绘班次",
                "db_table": "terrain_survey_shift",
            },
        ),
    ]
